test_that("recode_msigdbh formats MSigDB gene set names correctly", {
  expect_equal(
    recode_msigdbh(c(
      "HALLMARK_ADIPOGENESIS",
      "HALLMARK_ALLOGRAFT_REJECTION",
      "HALLMARK_ANDROGEN_RESPONSE",
      "HALLMARK_ANGIOGENESIS",
      "HALLMARK_APICAL_JUNCTION",
      "HALLMARK_APICAL_SURFACE",
      "HALLMARK_APOPTOSIS",
      "HALLMARK_BILE_ACID_METABOLISM",
      "HALLMARK_CHOLESTEROL_HOMEOSTASIS",
      "HALLMARK_COAGULATION",
      "HALLMARK_COMPLEMENT",
      "HALLMARK_DNA_REPAIR",
      "HALLMARK_E2F_TARGETS",
      "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION",
      "HALLMARK_ESTROGEN_RESPONSE_EARLY",
      "HALLMARK_ESTROGEN_RESPONSE_LATE",
      "HALLMARK_FATTY_ACID_METABOLISM",
      "HALLMARK_G2M_CHECKPOINT",
      "HALLMARK_GLYCOLYSIS",
      "HALLMARK_HEDGEHOG_SIGNALING",
      "HALLMARK_HEME_METABOLISM",
      "HALLMARK_HYPOXIA",
      "HALLMARK_IL2_STAT5_SIGNALING",
      "HALLMARK_IL6_JAK_STAT3_SIGNALING",
      "HALLMARK_INFLAMMATORY_RESPONSE",
      "HALLMARK_INTERFERON_ALPHA_RESPONSE",
      "HALLMARK_INTERFERON_GAMMA_RESPONSE",
      "HALLMARK_KRAS_SIGNALING_DN",
      "HALLMARK_KRAS_SIGNALING_UP",
      "HALLMARK_MITOTIC_SPINDLE",
      "HALLMARK_MTORC1_SIGNALING",
      "HALLMARK_MYC_TARGETS_V1",
      "HALLMARK_MYC_TARGETS_V2",
      "HALLMARK_MYOGENESIS",
      "HALLMARK_NOTCH_SIGNALING",
      "HALLMARK_OXIDATIVE_PHOSPHORYLATION",
      "HALLMARK_P53_PATHWAY",
      "HALLMARK_PANCREAS_BETA_CELLS",
      "HALLMARK_PEROXISOME",
      "HALLMARK_PI3K_AKT_MTOR_SIGNALING",
      "HALLMARK_PROTEIN_SECRETION",
      "HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY",
      "HALLMARK_SPERMATOGENESIS",
      "HALLMARK_TGF_BETA_SIGNALING",
      "HALLMARK_TNFA_SIGNALING_VIA_NFKB",
      "HALLMARK_UNFOLDED_PROTEIN_RESPONSE",
      "HALLMARK_UV_RESPONSE_DN",
      "HALLMARK_UV_RESPONSE_UP",
      "HALLMARK_WNT_BETA_CATENIN_SIGNALING",
      "HALLMARK_XENOBIOTIC_METABOLISM"
    )),
    c(
      "Adipogenesis",
      "Allograft rejection",
      "Androgen response",
      "Angiogenesis",
      "Apical junction",
      "Apical surface",
      "Apoptosis",
      "Bile acid metabolism",
      "Cholesterol homeostasis",
      "Coagulation",
      "Complement",
      "DNA repair",
      "E2F targets",
      "Epithelial-mesenchymal transition",
      "Early estrogen response",
      "Late estrogen response",
      "Fatty acid metabolism",
      "G2/M checkpoint",
      "Glycolysis",
      "Hedgehog signaling",
      "Heme metabolism",
      "Hypoxia",
      "IL-2-STAT5 signaling",
      "IL-6/JAK/STAT3 signaling",
      "Inflammatory response",
      "IFN-\u03b1 response",
      "IFN-\u03b3 response",
      "KRAS signaling down",
      "KRAS signaling up",
      "Mitotic spindle",
      "mTORC1 signaling",
      "MYC targets V1",
      "MYC targets V2",
      "Myogenesis",
      "Notch signaling",
      "Oxidative phosphorylation",
      "p53 pathway",
      "Pancreas beta cells",
      "Peroxisome",
      "PI3K/AKT/mTOR pathway",
      "Protein secretion",
      "Reactive oxygen species pathway",
      "Spermatogenesis",
      "TGF-\u03b2 signaling",
      "TNF-\u03b1 signaling via NF-\u03baB",
      "Unfolded protein response",
      "UV response down",
      "UV response up",
      "Wnt/\u03b2-catenin signaling",
      "Xenobiotic metabolism"
    )
  )
})
